name: opened by person

on:
  issues:
    types:
      - opened
      - transferred
  pull_request_target:
    types:
      - opened

jobs:
  transfer-issue:
    name: person
    runs-on: ubuntu-latest
    if: github.actor == 'skedwards88'
    steps:

      - name: only if person
        run: echo it was me
    if: github.actor != 'skedwards88'
    steps:

      - name: only if not person
        run: echo should not print
